#!/usr/bin/env ruby

require 'colored'

abort( "Usage: #{__FILE__} <number>
        Will tell you human readable files size." ) if ARGV.size != 1

TERA_SIZE = 1099511627776.0
GIGA_SIZE = 1073741824.0
MEGA_SIZE = 1048576.0
KILO_SIZE = 1024.0

filesize = ARGV[0].to_i

# Return the file size with a readable style.
def readable_file_size(size, precision)
  case
  when size == 1 then "1 Byte"
  when size < KILO_SIZE then "%d Bytes" % size
  when size < MEGA_SIZE then "%.#{precision}f KB" % (size / KILO_SIZE)
  when size < GIGA_SIZE then "%.#{precision}f MB" % (size / MEGA_SIZE)
  when size < TERA_SIZE then "%.#{precision}f GB" % (size / GIGA_SIZE)
  else "%.#{precision}f TB" % (size / TERA_SIZE)
  end
end

puts readable_file_size(filesize, 2)
